name: CMake

on:
  # push:
    # branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    continue-on-error: false
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install tools
      # Install the tools we need
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang-tidy-12 ccache libgflags-dev graphviz doxygen libxerces-c-dev librdkafka-dev
        sudo snap install cmake --classic

    - name: Check code formatting
      run: |
        out=$(git clang-format-12 --binary=clang-format-12 --diff HEAD^)
        [ "$out" = "no modified files to format" ] && exit 0
        [ "$out" = "clang-format did not modify any files" ] && exit 0
        echo "Badly formatted files:"
        git clang-format-12 --binary=clang-format-12 HEAD^
        exit 1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Ninja Multi-Config"

    # We can build the check target immediately, but building the default
    # target first allows us to see if the CI fails because of the build
    # or the test.
    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config Debug
        cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      run: |
        cmake --build ${{github.workspace}}/build --config Debug --target check
        cmake --build ${{github.workspace}}/build --config Release --target check
